# Generated by Django 3.1.2 on 2020-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('position', models.CharField(choices=[('internship', 'Internship'), ('employee', 'Employee')], default='employee', max_length=100)),
                ('photo', models.ImageField(upload_to='employee')),
            ],
        ),
    ]
