# Generated by Django 3.1.2 on 2020-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
